gpg_keys:
- key: https://download.docker.com/linux/ubuntu/gpg
- key: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key

repositories:
- repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
- repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/" #k8s not available yet for Bionic (Ubuntu 18.04)

apt_packages:
- name: apt-transport-https
- name: curl
- name: net-tools
- name: bash-completion

docker_packages:
- name: docker-ce
- name: docker-ce-cli
- name: containerd.io
- name: docker-buildx-plugin
- name: docker-compose-plugin

# k8s_packages:
# - name: kubectl=1.26.5-00
# - name: kubeadm=1.26.5-00
# - name: kubelet=1.26.5-00
